services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./backend/src/:/app/src/
  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=wemeet
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=wemeet
      - MYSQL_DATABASE=wemeet
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30
